version: '3.7'

services:
    # linkedu_service:
    #     build: .
    #     volumes:
    #         - .:/app/
    #         - static_files:/app/static_files

    #     container_name: linkedu_service
    #     expose:
    #         - 8000
    #     env_file:
    #         - ./LinkedU/.env
    #     networks:
    #         - linkedu-net
    #     restart: always
    #     depends_on:
    #         - linkedu_db_service

    lms_db_service:
        image: postgres
        restart: always
        volumes:
            - lms-vol:/var/lib/postgresql/data
        # networks:
        #     - lms-net
        container_name: lms_db
        env_file:
            - ./LMS/.env
        ports:
            - 5432:5432

    # nginx:
    #     build: ./nginx
    #     volumes:
    #         - static_files:/app/static_files
    #     ports:
    #         - "8000:80"
    #     networks:
    #         - linkedu-net

    #     depends_on:
    #         - linkedu_service

volumes:
    # static_files:
    lms-vol:


# networks:
    # linkedu-net: